#! /bin/sh

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:
runlevel=S
prevlevel=N
umask 022
export PATH runlevel prevlevel

#
#	Trap CTRL-C &c only in this shell so we can interrupt subprocesses.
#
trap ":" INT QUIT TSTP
/bin/hostname FriendlyARM

[ -e /proc/1 ]    || /bin/mount -n -t proc  none /proc
[ -e /sys/class ] || /bin/mount -n -t sysfs none /sys
[ -e /dev/tty ]   || /bin/mount    -t ramfs none /dev
/bin/mount -n -t usbfs none /proc/bus/usb

echo /sbin/mdev > /proc/sys/kernel/hotplug
/sbin/mdev -s
/bin/hotplug
# mounting file system specified in /etc/fstab
mkdir -p /dev/pts
mkdir -p /dev/shm
/bin/mount -n -t devpts none /dev/pts -o mode=0622
/bin/mount -n -t tmpfs tmpfs /dev/shm
/bin/mount -n -t ramfs none /tmp
/bin/mount -n -t ramfs none /var
mkdir -p /var/empty
mkdir -p /var/log
mkdir -p /var/lock
mkdir -p /var/run
mkdir -p /var/tmp

/sbin/hwclock -s

syslogd
/etc/rc.d/init.d/netd start
#echo "                        " > /dev/tty1
#echo "Starting networking..." > /dev/tty1
#sleep 1
#/etc/rc.d/init.d/httpd start
#echo "                        " > /dev/tty1
#echo "Starting web server..." > /dev/tty1
#sleep 1
#/etc/rc.d/init.d/leds start
#echo "                        " > /dev/tty1
#echo "Starting leds service..." > /dev/tty1
#echo "                        "
#sleep 1

#echo "                        " > /dev/tty1
#/etc/rc.d/init.d/alsaconf start
#echo "Loading sound card config..." > /dev/tty1
#echo "                        "

# install additional modules
#modprobe ft5x06_ts 2>/dev/null
#modprobe goodix_touch 2>/dev/null
#modprobe ov9650 2>/dev/null
#modprobe tvp5150_tiny210 2>/dev/null
#modprobe rtl8192cu 2>/dev/null
#modprobe ath9k_htc 2>/dev/null
#modprobe rt73usb 2>/dev/null                  
#modprobe rt2800usb 2>/dev/null
#modprobe zd1211rw 2>/dev/null
#modprobe libertas_sdio 2>/dev/null

/sbin/ifconfig lo 127.0.0.1
/etc/init.d/ifconfig-eth0
fa-network-service
hdmi-service autostart

# /opt/360box/apktools-service
# /opt/360box/run.sh &

#/bin/qtopia &
#echo "                                  " > /dev/tty1
#echo "Starting Qtopia, please waiting..." > /dev/tty1

mount /dev/sda1 /udisk
/bin/qt4 &
#cd /opt/
#./mobilebox -qws &
#hotplug