#!/bin/sh

[ -e /var/run/ppp0.pid ] && exit 1
rm /var/run/ppp0-ok 2>/dev/null
>/var/run/ppp0.pid
( pppd call $1 > /var/run/pppd-output 2>&1; rm /var/run/ppp0.pid; rm /var/run/ppp0-ok; rm /var/run/pppd-output; rm /var/run/pppd2.tdb )&
