#!/bin/sh
[ -e /var/run/ppp0.pid ] && exit 1

rm /var/run/ppp0-ok 2>/dev/null
set-modem-bps ${1:-/dev/ttySAC1}
>/var/run/ppp0.pid
( pppd \
    ${1:-/dev/ttySAC1} \
    115200 \
    connect 'chat -s -v -f /etc/ppp/gprs_connect' \
    disconnect 'chat -s -v -f /etc/ppp/gprs_disconnect' \
    defaultroute \
    user cmnet \
    crtscts \
    modem \
    usepeerdns \
    nodetach \
    debug; rm /var/run/ppp0.pid) &
